// Autogenerated, do not edit. All changes will be lost.

/// <reference path="../node_modules/reflect-metadata/Reflect.d.ts" />
/// <reference path="../node_modules/retyped-iscroll-tsd-ambient/iscroll.d.ts" />